# Generated by Django 3.2.8 on 2021-10-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'pokemon',
            },
        ),
        migrations.CreateModel(
            name='PokemonAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=512)),
                ('function', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'pokemon_abilities',
            },
        ),
        migrations.CreateModel(
            name='UserPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_index=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonService.pokemon')),
                ('pokemon_ablities', models.ManyToManyField(to='pokemonService.PokemonAbilities')),
            ],
            options={
                'db_table': 'user_pokemon',
            },
        ),
    ]
