# Generated by Django 3.2.8 on 2021-10-17 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_index=True)),
                ('fight', models.IntegerField(db_index=True)),
                ('score_earned', models.IntegerField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'leaderboard_history',
            },
        ),
        migrations.CreateModel(
            name='UserLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_index=True)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'user_leaderboard',
            },
        ),
    ]
