# Generated by Django 3.2.8 on 2021-10-17 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('locality', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=512)),
                ('other_settings', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userService.user')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('device_info', models.CharField(max_length=512)),
                ('last_logged_in', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('current_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('uninstalled', 'uninstalled')], max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userService.user')),
            ],
            options={
                'db_table': 'session',
            },
        ),
    ]
